apps/blog/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
# from .views import goview
from .views import (IndexView, DetailView, CategoryView, TagView, AboutView,
                    SilianView, MySearchView, ArchiveView, TimelineView, CommentView, addComment, commentList)

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),  # 主页，自然排序
    url(r'^hot/$', IndexView.as_view(), {'sort': 'v'}, name='index_hot'),  # 主页，按照浏览量排序
    url(r'^article/(?P<slug>[\w-]+)/$', DetailView.as_view(), name='detail'),  # 文章内容页
    url(r'^category/(?P<slug>[\w-]+)/$', CategoryView.as_view(), name='category'),
    url(r'^category/(?P<slug>[\w-]+)/hot/$', CategoryView.as_view(), {'sort': 'v'},
        name='category_hot'),
    url(r'^tag/(?P<slug>[\w-]+)/$', TagView.as_view(), name='tag'),
    url(r'^tag/(?P<slug>[\w-]+)/hot/$', TagView.as_view(), {'sort': 'v'}, name='tag_hot'),
    url(r'^about/$', AboutView, name='about'),  # About页面
    url(r'^timeline/$', TimelineView.as_view(), name='timeline'),  # timeline页面
    url(r'archive/$', ArchiveView.as_view(), name='archive'),  # 归档页面
    url(r'^silian\.xml$', SilianView.as_view(content_type='application/xml'), name='silian'),  # 死链页面
    url(r'^search/$', MySearchView.as_view(), name='search_view'),  # 全文搜索
    url(r'^comment/$', CommentView, name='comment'),  # 留言页面
    url(r'^addComment/$', addComment, name='add_comment'),  # 新增留言
    url(r'^commentList/$', commentList, name='comment_list'),  # 查询留言列表


]

apps/comment/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from .views import AddcommentView, NotificationView, mark_to_read, mark_to_delete

urlpatterns = [
    url(r'^add/$', AddcommentView, name='add_comment'),
    url(r'^notification/$', NotificationView, name='notification'),
    url(r'^notification/no-read/$', NotificationView, {'is_read': 'false'}, name='notification_no_read'),
    url(r'^notification/mark-to-read/$', mark_to_read, name='mark_to_read'),
    url(r'^notification/mark-to-delete/$', mark_to_delete, name='mark_to_delete'),
]

izone/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.views.generic import TemplateView

from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import ArticleSitemap, CategorySitemap, TagSitemap
from blog.feeds import AllArticleRssFeed

from rest_framework.routers import DefaultRouter
from api import views as api_views

if settings.API_FLAG:
    router = DefaultRouter()
    router.register(r'users',api_views.UserListSet)
    router.register(r'articles',api_views.ArticleListSet)
    router.register(r'tags',api_views.TagListSet)
    router.register(r'categorys',api_views.CategoryListSet)
    router.register(r'timelines',api_views.TimelineListSet)
    router.register(r'toollinks',api_views.ToolLinkListSet)

# 网站地图
sitemaps = {
    'articles': ArticleSitemap,
    'tags': TagSitemap,
    'categories': CategorySitemap
}

urlpatterns = [
    url(r'^adminx/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),  # allauth
    url(r'^accounts/', include('oauth.urls', namespace='oauth')),  # oauth,只展现一个用户登录界面
    url('', include('blog.urls', namespace='blog')),  # blog
    url(r'^comment/',include('comment.urls',namespace='comment')), # comment
    url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')), # robots
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'), # 网站地图
    url(r'^feed/$', AllArticleRssFeed(), name='rss'),   # rss订阅
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # 加入这个才能显示media文件

if settings.API_FLAG:
    urlpatterns.append(url(r'^api/v1/',include(router.urls,namespace='api')))    # restframework

if settings.TOOL_FLAG:
    urlpatterns.append(url(r'^tool/', include('tool.urls',namespace='tool')))    # tool

apps/comment/models.py
from django.db import models
from django.conf import settings
from blog.models import Article

import markdown
import emoji


class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='%(class)s_related', verbose_name='评论人')
    create_date = models.DateTimeField('创建时间', auto_now_add=True)
    content = models.TextField('评论内容')
    parent = models.ForeignKey('self', verbose_name='父评论', related_name='%(class)s_child_comments', blank=True,
                               null=True)
    rep_to = models.ForeignKey('self', verbose_name='回复', related_name='%(class)s_rep_comments', blank=True, null=True)

    class Meta:
        '''这是一个元类，用来继承的'''
        abstract = True

    def __str__(self):
        return self.content[:20]

    def content_to_markdown(self):
        # 先转换成emoji然后转换成markdown,'escape':所有原始HTML将被转义并包含在文档中
        to_emoji_content = emoji.emojize(self.content, use_aliases=True)
        to_md = markdown.markdown(to_emoji_content,
                                  safe_mode='escape',
                                  extensions=[
                                      'markdown.extensions.extra',
                                      'markdown.extensions.codehilite',
                                  ])
        return to_md

class ArticleComment(Comment):
    belong = models.ForeignKey(Article, related_name='article_comments', verbose_name='所属文章')

    class Meta:
        verbose_name = '文章评论'
        verbose_name_plural = verbose_name
        ordering = ['create_date']

class Notification(models.Model):
    create_p = models.ForeignKey(settings.AUTH_USER_MODEL,verbose_name='提示创建者',related_name='notification_create')
    get_p = models.ForeignKey(settings.AUTH_USER_MODEL,verbose_name='提示接收者',related_name='notification_get')
    comment = models.ForeignKey(ArticleComment,verbose_name='所属评论',related_name='the_comment')
    create_date = models.DateTimeField('提示时间',auto_now_add=True)
    is_read = models.BooleanField('是否已读',default=False)

    def mark_to_read(self):
        self.is_read = True
        self.save(update_fields=['is_read'])

    class Meta:
        verbose_name = '提示信息'
        verbose_name_plural = verbose_name
        ordering = ['-create_date']

    def __str__(self):
        return '{}@了{}'.format(self.create_p,self.get_p)

apps/blog/views.py
from django.shortcuts import get_object_or_404, render
from django.utils.text import slugify
from django.views import generic
from django.conf import settings
from .models import Article, Tag, Category, Timeline, Silian
from django.core.cache import cache
from django.views.decorators.http import require_POST

from markdown.extensions.toc import TocExtension  # 锚点的拓展
import markdown
import time, datetime

from haystack.generic_views import SearchView  # 导入搜索视图
from haystack.query import SearchQuerySet


# Create your views here.

class ArchiveView(generic.ListView):
    model = Article
    template_name = 'blog/archive.html'
    context_object_name = 'articles'
    paginate_by = 200
    paginate_orphans = 50


class IndexView(generic.ListView):
    model = Article
    template_name = 'blog/index.html'
    context_object_name = 'articles'
    paginate_by = getattr(settings, 'BASE_PAGE_BY', None)
    paginate_orphans = getattr(settings, 'BASE_ORPHANS', 0)

    def get_ordering(self):
        ordering = super(IndexView, self).get_ordering()
        sort = self.kwargs.get('sort')
        if sort == 'v':
            return ('-views', '-update_date', '-id')
        return ordering


class DetailView(generic.DetailView):
    model = Article
    template_name = 'blog/detail.html'
    context_object_name = 'article'

    def get_object(self):
        obj = super(DetailView, self).get_object()
        # 设置浏览量增加时间判断,同一篇文章两次浏览超过半小时才重新统计阅览量,作者浏览忽略
        u = self.request.user
        ses = self.request.session
        the_key = 'is_read_{}'.format(obj.id)
        is_read_time = ses.get(the_key)
        if u != obj.author:
            if not is_read_time:
                obj.update_views()
                ses[the_key] = time.time()
            else:
                now_time = time.time()
                t = now_time - is_read_time
                if t > 60 * 30:
                    obj.update_views()
                    ses[the_key] = time.time()
        # 获取文章更新的时间，判断是否从缓存中取文章的markdown,可以避免每次都转换
        ud = obj.update_date.strftime("%Y%m%d%H%M%S")
        md_key = '{}_md_{}'.format(obj.id, ud)
        cache_md = cache.get(md_key)
        if cache_md:
            md = cache_md
        else:
            md = markdown.Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
                TocExtension(slugify=slugify),
            ])
            cache.set(md_key, md, 60 * 60 * 12)
        obj.body = md.convert(obj.body)
        obj.toc = md.toc
        return obj


class CategoryView(generic.ListView):
    model = Article
    template_name = 'blog/category.html'
    context_object_name = 'articles'
    paginate_by = getattr(settings, 'BASE_PAGE_BY', None)
    paginate_orphans = getattr(settings, 'BASE_ORPHANS', 0)

    def get_ordering(self):
        ordering = super(CategoryView, self).get_ordering()
        sort = self.kwargs.get('sort')
        if sort == 'v':
            return ('-views', '-update_date', '-id')
        return ordering

    def get_queryset(self, **kwargs):
        queryset = super(CategoryView, self).get_queryset()
        cate = get_object_or_404(Category, slug=self.kwargs.get('slug'))
        return queryset.filter(category=cate)

    def get_context_data(self, **kwargs):
        context_data = super(CategoryView, self).get_context_data()
        cate = get_object_or_404(Category, slug=self.kwargs.get('slug'))
        context_data['search_tag'] = '文章分类'
        context_data['search_instance'] = cate
        return context_data


class TagView(generic.ListView):
    model = Article
    template_name = 'blog/tag.html'
    context_object_name = 'articles'
    paginate_by = getattr(settings, 'BASE_PAGE_BY', None)
    paginate_orphans = getattr(settings, 'BASE_ORPHANS', 0)

    def get_ordering(self):
        ordering = super(TagView, self).get_ordering()
        sort = self.kwargs.get('sort')
        if sort == 'v':
            return ('-views', '-update_date', '-id')
        return ordering

    def get_queryset(self, **kwargs):
        queryset = super(TagView, self).get_queryset()
        tag = get_object_or_404(Tag, slug=self.kwargs.get('slug'))
        return queryset.filter(tags=tag)

    def get_context_data(self, **kwargs):
        context_data = super(TagView, self).get_context_data()
        tag = get_object_or_404(Tag, slug=self.kwargs.get('slug'))
        context_data['search_tag'] = '文章标签'
        context_data['search_instance'] = tag
        return context_data


def AboutView(request):
    site_date = datetime.datetime.strptime('2018-04-12','%Y-%m-%d')
    return render(request, 'blog/about.html',context={'site_date':site_date})


class TimelineView(generic.ListView):
    model = Timeline
    template_name = 'blog/timeline.html'
    context_object_name = 'timeline_list'


class SilianView(generic.ListView):
    model = Silian
    template_name = 'blog/silian.xml'
    context_object_name = 'badurls'


def CommentView(request):
    '''
    留言 页面
    :param request:
    :return:
    '''
    site_date = datetime.datetime.strptime('2018-04-12','%Y-%m-%d')
    context = {}
    context['site_date'] = site_date
    context['hello'] = "Hello World"

    messages = get_messages_from_csv()

    context['contexts'] = messages
    print(messages)
    return render(request, 'blog/comment.html', context=context)


import time
import csv

@require_POST
def addComment(request):
    '''
        新增留言
        :param request:
        :return:
        '''
    print("新增留言")
    data = request.POST
    message = data.get('message')
    user_name = ""
    # 优化格式化化版本
    time_str = time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(time.time()))
    stu1 = [user_name, message, time_str]

    write_message_to_csv(stu1)

    messages = get_messages_from_csv()

    context = {}
    context['message'] = "添加留言成功"
    context['contexts'] = messages
    print(messages)
    return render(request, 'blog/comment.html', context=context)


def get_messages_from_csv():

    f = open('data/message.cvs', 'r')
    csvreader = csv.reader(f)
    csvreader = list(csvreader)

    result = []
    if csvreader == None or len(csvreader) == 0:
        return result

    one_line = {}
    one_line['name'] = '欢迎加入地图数据爬取交流群'
    one_line['time'] = '2019-09-17 00:00:0'
    result.append(one_line)

    csvreader.reverse()
    for one in csvreader:
        one_line = {}
        one_line['name'] = one[1]
        one_line['time'] = one[2]
        result.append(one_line)

    return result



def write_message_to_csv(data):
    '''
    留言写入CSV
    :param data:
    :return:
    '''
    # 打开文件，写模式为追加'a'
    out = open('data/message.cvs', 'a', newline='')
    # 设定写入模式
    csv_write = csv.writer(out, dialect='excel')
    # 写入具体内容
    csv_write.writerow(data)

def commentList(request):
    '''
            查询留言列表
            :param request:
            :return:
            '''
    print("查询留言列表")
    pass

# 重写搜索视图，可以增加一些额外的参数，且可以重新定义名称
class MySearchView(SearchView):
    context_object_name = 'search_list'
    paginate_by = getattr(settings, 'BASE_PAGE_BY', None)
    paginate_orphans = getattr(settings, 'BASE_ORPHANS', 0)
    queryset = SearchQuerySet().order_by('-views')

apps/comment/views.py
from django.shortcuts import render
from blog.models import Article
from .models import ArticleComment, Notification
from django.conf import settings
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from datetime import datetime
from django.shortcuts import get_object_or_404
from . import handlers

user_model = settings.AUTH_USER_MODEL


@login_required
@require_POST
def AddcommentView(request):
    if request.is_ajax():
        data = request.POST
        new_user = request.user
        new_content = data.get('content')
        article_id = data.get('article_id')
        rep_id = data.get('rep_id')
        the_article = Article.objects.get(id=article_id)
        if not rep_id:
            new_comment = ArticleComment(author=new_user, content=new_content, belong=the_article, parent=None,
                                         rep_to=None)
        else:
            new_rep_to = ArticleComment.objects.get(id=rep_id)
            new_parent = new_rep_to.parent if new_rep_to.parent else new_rep_to
            new_comment = ArticleComment(author=new_user, content=new_content, belong=the_article, parent=new_parent,
                                         rep_to=new_rep_to)
        new_comment.save()
        new_point = '#com-' + str(new_comment.id)
        return JsonResponse({'msg': '评论提交成功！', 'new_point': new_point})
    return JsonResponse({'msg': '评论失败！'})


@login_required
def NotificationView(request, is_read=None):
    '''展示提示消息列表'''
    now_date = datetime.now()
    return render(request, 'comment/notification.html', context={'is_read': is_read, 'now_date': now_date})


@login_required
@require_POST
def mark_to_read(request):
    '''将一个消息标记为已读'''
    if request.is_ajax():
        data = request.POST
        user = request.user
        id = data.get('id')
        info = get_object_or_404(Notification, get_p=user, id=id)
        info.mark_to_read()
        return JsonResponse({'msg': 'mark success'})
    return JsonResponse({'msg': 'miss'})


@login_required
@require_POST
def mark_to_delete(request):
    '''将一个消息删除'''
    if request.is_ajax():
        data = request.POST
        user = request.user
        id = data.get('id')
        info = get_object_or_404(Notification, get_p=user, id=id)
        info.delete()
        return JsonResponse({'msg': 'delete success'})
    return JsonResponse({'msg': 'miss'})

apps/blog/templates/blog/about.html
{% extends 'blog/base.html' %}
{% load static %}

{% block head_title %}关于网站{% endblock %}
{% block metas %}
<meta name="description"
      content="本网站是一个采用django+bootstrap4搭建的个人博客，本着学习和分享的精神，博客项目开源，源代码可以到我的Github中查看，网站建站历程可以查看页面Timeline内容。">
<meta name="keywords" content="网站About页面,关于网站,关于博主,关于站长">
{% endblock %}


{% block base_content %}
<div class="container">
    <div class="row">
        <div class="col-lg-8" style="line-height:2">
            <div class="card rounded-0 border-0 p-3 f-16">
                <h2 class="font-weight-bold">关于网站</h2>
                <hr style="margin: .1rem;dashed #333;"/>
                <ul class="pl-4 ml-2">
                	<li>有问题请加群：626697156</li>
                </ul>
                <h2 class="mt-2 font-weight-bold">功能介绍</h2>
                <hr style="margin: .1rem;dashed #333;"/>
                <ul class="pl-4 ml-2">
                    <li>腾讯位置大数据爬取：基于腾讯位置大数据实时采集人流量数据,缺点是精度不够高</li>
                    <li>宜出行人流量爬取：基于微信宜出行实时采集人流量数据，精度还可以</li>
                    <li>热力图在线可视化：上传有经纬度、人数的CSV文件，即可可视化人流量分布情况</li>
                    <li>POI数据爬取：根据城市以及关键字爬取POI兴趣点数据</li>
                    <li>划分矩形网格爬取POI数据</li>
                    <li>渔网坐标生成工具：将大矩形坐标范围划分为多个渔网网格</li>
                    <li>百度POI边界采集工具：根据百度POI数据的UID采集POI对应的边界坐标</li>
                    <li>POI数据在线可视化：上传带有经纬度的EXCEL文件，即可可视化展示POI点分布情况</li>
                    <li>坐标拾取工具：点击地图即可得到当前点的经纬度，并提供GCJ20、BD09、WGS84三种坐标</li>
                    <li>坐标转换工具：上传带有经纬度的数据，可将经纬度转换为指定的坐标系数据</li>
                </ul>
                
              
                
                <h2 class="mt-2 font-weight-bold">TODO</h2>
                <hr style="margin: .1rem;dashed #333;"/>
                <ul class="pl-4 ml-2">
                	  <li>地理数据可视化平台</li>
                    <li>地图圈选工具</li>
                    <li>地图测距</li>
                    <li>公交线路查询</li>
                    <li>地铁线路查询</li>
                    <li>全国各个行政区划边界数据采集</li>
                		<li>更多功能正在构思中，有想法的也可留言，或者加群讨论。</li>
                </ul>
                
                
            </div>
        </div>
        <div class="col-lg-4">
            {% include 'blog/tags/base_right.html' %}
        </div>
    </div>
</div>
{% endblock %}

apps/blog/templates/blog/archive.html
{% extends "blog/base.html" %}
{% load cache %}
{% load static %}
{% load humanize %}
{% load blog_tags %}

{% block head_title %}BLT-LEAD文章归档{% endblock %}
{% block metas %}
<meta name="description" content="BLT-LEAD文章归档，按照年份、月份对整站文章进行归档排序">
<meta name="keywords" content="博客,博客归档">
{% endblock %}

{% block top-file %}
<style type="text/css">
.archive {
    line-height:2;
}
</style>
{% endblock %}

{% block base_content %}
<div class="container">
    <div class="row">
        {% cache 3600 'cache_archive_html_tag' %}
        <div class="col-lg-8">
            <div class="card border-0 rounded-0 mb-3">
                <div class="card-body f-16 archive">
                    {% regroup articles by create_date.year as year_list %}
                    <ul class="pl-4">
                        {% for article in year_list %}
                        <li>{{ article.grouper }} 年
                            {% regroup article.list by create_date.month as month_list %}
                            <ul class="pl-4">
                                {% for each in month_list %}
                                <li>{{ each.grouper }} 月 (共 {{ each.list|length }} 篇)
                                    <ul class="pl-4">
                                        {% for item in each.list %}
                                        <li class="text-info">{{ item.create_date|date:'m-d' }}&nbsp;&nbsp;<a href="{{ item.get_absolute_url }}">{{ item.title }}</a></li>
                                        {% endfor %}
                                    </ul>
                                </li>
                                {% endfor %}
                            </ul>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            {% if is_paginated %}{% load_pages %}{% endif %}
        </div>
        {% endcache %}
        <div class="col-lg-4 d-none d-lg-block">
            {% include 'blog/tags/base_right.html' %}
        </div>
    </div>
</div>
{% endblock %}

apps/blog/templates/blog/category.html
{% extends "blog/base.html" %}
{% load static %}
{% load humanize %}
{% load blog_tags %}

{% block head_title %}{{ search_instance.name }}_{{ search_tag }}{% endblock %}
{% block metas %}
    <meta name="description" content="{{ search_instance.description }}">
    <meta name="keywords" content="{{ search_instance.name }}">
{% endblock %}

{% block base_content %}
<div class="container">
    <div class="row">
        <div class="col-lg-8">
            <div class="description bg-white px-3 pt-3 pb-1">
                <p class="float-right mb-0">共<span class="mx-2 text-info">{{ paginator.count }}</span>篇</p>
                <h1 class="f-17"><strong>{{ search_tag }}：{{ search_instance.name }}</strong></h1>
                <p class="f-16">{{ search_instance.description }}</p>
            </div>
            <div class="text-secondary font-weight-bold py-2 f-15 choice">
                {% url 'blog:category' search_instance.slug as base_category %}
                {% url 'blog:category_hot' search_instance.slug as hot_category %}
                <a class="pb-2 {% if request.path == base_category %}active{% endif %}" href="{{ base_category }}">
                    <i class="fa fa-bars mr-1"></i>时间排序</a>
                <a class="pb-2 ml-4 {% if request.path == hot_category %}active{% endif %}" href="{{ hot_category }}">
                    <i class="fa fa-fire mr-1"></i>热度排序</a>
            </div>
            {% load_article_summary articles %}
            {% if is_paginated %}{% load_pages %}{% endif %}
        </div>
        <div class="col-lg-4">
            {% include 'blog/tags/base_right.html' %}
        </div>
    </div>
</div>
{% endblock %}

apps/blog/templates/blog/comment.html
{% extends 'blog/base.html' %}
{% load static %}

{% block head_title %}留言{% endblock %}
{% block metas %}
<meta name="description"
      content="本网站是一个采用django+bootstrap4搭建的个人博客，本着学习和分享的精神，博客项目开源，源代码可以到我的Github中查看，网站建站历程可以查看页面Timeline内容。">
<meta name="keywords" content="网站About页面,关于网站,关于博主,关于站长">
{% endblock %}


{% block base_content %}
<div class="container">
    <div class="row">
        <div class="col-lg-8" style="line-height:2">
            <div class="card rounded-0 border-0 p-3 f-16">
                <h2 class="font-weight-bold">发表留言</h2>
                <hr style="margin: .1rem;dashed #333;"/>
               <form method="post" action="{% url 'blog:add_comment' %}">
				{% if message %}
					  <p style="color:red;margin-left:150px;;height:30px;margin-bottom:20px">{{ message }}</p>
					  {% endif %}
				<div class="mb-3">
				    <textarea class="form-control" name="message" placeholder="随便说点意见或者建议吧..." rows="3"></textarea>
				    
				    <button type="submit" class="btn btn-info btn-sm rounded-0">确定</button>
				    
				</div>
				
				{% csrf_token %}
			</form>
                <h2 class="mt-2 font-weight-bold">留言列表</h2>
                <hr style="margin: .1rem;dashed #333;"/>
                <ul class="pl-4 ml-2">
                    {% if contexts %}
					  {% for row in contexts %}
							<li>{{ row.name }}       {{ row.time }}</li>
					  {% endfor %}
					{% endif %}
                </ul>
               
                
            </div>
        </div>
        <div class="col-lg-4">
            {% include 'blog/tags/base_right.html' %}
        </div>
        
        <script type="text/javascript">
        	//alert("查询留言列表");
        </script>
    </div>
</div>
{% endblock %}

apps/blog/templates/blog/index.html
{% extends "blog/base.html" %}
{% load static %}
{% load humanize %}
{% load blog_tags %}

{% block head_title %} {{ site_end_title }}_{{ site_description }}{% endblock %}
{% block metas %}
    <meta name="description" content="{{ site_description }}">
    <meta name="keywords" content="{{ site_keywords }}">
    <!--站长验证-->
    <meta name="baidu-site-verification" content="YCoD4WTuGF" />
    <meta name="360-site-verification" content="5492df7d63c9ceb707eff60d6cf699e1" />
    <meta name="sogou_site_verification" content="czcxwE2sdj"/>
    <meta name="shenma-site-verification" content="169f4055c7f0323f020d0d238a2bec48_1523704037">
{% endblock %}

{% block base_content %}
<div class="container">
    <div class="row">
        <div class="col-lg-8">
            {% include 'blog/tags/carousel.html' %}
            <div class="text-secondary font-weight-bold py-2 f-15 choice">
                {% url 'blog:index' as base_index %}
                {% url 'blog:index_hot' as hot_index %}
                <a class="pb-2 {% if request.path == base_index %}active{% endif %}" href="{{ base_index }}">
                    <i class="fa fa-bars mr-1"></i>时间排序</a>
                <a class="pb-2 ml-4 {% if request.path == hot_index %}active{% endif %}" href="{{ hot_index }}">
                    <i class="fa fa-fire mr-1"></i>热度排序</a>
            </div>
            {% load_article_summary articles %}
            {% if is_paginated %}{% load_pages %}{% endif %}
        </div>
        <div class="col-lg-4">
            {% include 'blog/tags/base_right.html' %}
        </div>
    </div>
</div>
{% endblock %}

apps/blog/templates/blog/tag.html
{% extends "blog/base.html" %}
{% load static %}
{% load humanize %}
{% load blog_tags %}

{% block head_title %}{{ search_instance.name }}_{{ search_tag }}{% endblock %}
{% block metas %}
<meta name="description" content="{{ search_instance.description }}">
<meta name="keywords" content="{{ search_instance.name }}">
{% endblock %}

{% block base_content %}
<div class="container">
    <div class="row">
        <div class="col-lg-8">
            <div class="description bg-white px-3 pt-3 pb-1">
                <p class="float-right mb-0">共<span class="mx-2 text-info">{{ paginator.count }}</span>篇</p>
                <h1 class="f-17"><strong>{{ search_tag }}：{{ search_instance.name }}</strong></h1>
                <p class="f-16">{{ search_instance.description }}</p>
            </div>
            <div class="text-secondary font-weight-bold py-2 f-15 choice">
                {% url 'blog:tag' search_instance.slug as base_tag %}
                {% url 'blog:tag_hot' search_instance.slug as hot_tag %}
                <a class="pb-2 {% if request.path == base_tag %}active{% endif %}" href="{{ base_tag }}">
                    <i class="fa fa-bars mr-1"></i>时间排序</a>
                <a class="pb-2 ml-4 {% if request.path == hot_tag %}active{% endif %}" href="{{ hot_tag }}">
                    <i class="fa fa-fire mr-1"></i>热度排序</a>
            </div>
            {% load_article_summary articles %}
            {% if is_paginated %}{% load_pages %}{% endif %}
        </div>
        <div class="col-lg-4">
            {% include 'blog/tags/base_right.html' %}
        </div>
    </div>
</div>
{% endblock %}