apps/tool/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from .views import (Toolview, BD_pushview, bd_api_view, BD_pushview_site, bd_api_site, Link_testview,
                    Link_test_api, regexview, regex_api, useragent_view, useragent_api, html_characters,
                    tencentview, tencent_data, poi_view, poi_data, getSubdistrict, poi_visual, upload,heatmap_visual

        , coord_view, poicoordtransform, coordpick, yichuxing_view, yichuxing_data, polygon_view, poi_polygon_data
        , gridview, grid_generate, boundaryview, boundarydata, common_file_upload, common_file_download, common_file_download_coord,
                    bmappoi, bmappoidata, common_file_download_yichuxing_chengdu)

urlpatterns = [
    url(r'^$', Toolview, name='total'),  # 工具汇总页
    url(r'^baidu-linksubmit/$', BD_pushview, name='baidu_push'),  # 百度主动推送
    url(r'^baidu-linksubmit/ajax/$', bd_api_view, name='baidu_push_api'),  # 百度推送ajax
    url(r'^baidu-linksubmit-for-sitemap/$', BD_pushview_site, name='baidu_push_site'),  # 百度主动推送sitemap
    url(r'^baidu-linksubmit-for-sitemap/ajax/$', bd_api_site, name='baidu_push_api_site'),
    url(r'^link-test/$', Link_testview, name='link_test'),  # 友链检测
    url(r'^link-test/ajax/$', Link_test_api, name='link_test_api'),
    url(r'^regex/$', regexview, name='regex'),  # 正则表达式在线
    url(r'^regex/ajax/$', regex_api, name='regex_api'),
    url(r'^user-agent/$', useragent_view, name='useragent'),  # user-agent生成器
    url(r'^user-agent/ajax/$', useragent_api, name='useragent_api'),
    url(r'^html-special-characters/$', html_characters, name='html_characters'),  # HTML特殊字符查询
    url(r'^tencet/$', tencentview, name='tencent'),  # 腾讯位置大数据爬取页面
    url(r'^tencentdata/$', tencent_data, name='tencent_data'),  # 腾讯位置大数据爬取
    url(r'^poiview/$', poi_view, name='poi_view'),  # POI数据爬取页面
    url(r'^poidata/$', poi_data, name='poi_data'),  # POI数据爬取
    url(r'^subdistrictdata/$', getSubdistrict, name='subdistrict_data'),  # P获取行政区数据
    url(r'^poi_visual/$', poi_visual, name='poi_visual'),  # P获取行政区数据
    url(r'^upload/$', upload, name='upload'),  # P获取行政区数据
    url(r'^heatmap_visual/$', heatmap_visual, name='heatmap_visual'),  # 热力图可视化页面
    url(r'^coord_view/$', coord_view, name='coord_view'),  # 坐标转换页面
    url(r'^poicoordtransform/$', poicoordtransform, name='poicoordtransform'),  # 坐标转换
    url(r'^coordpick/$', coordpick, name='coordpick'),  # 坐标拾取页面
    url(r'^yichuxing_view/$', yichuxing_view, name='yichuxing'),  # 宜出行数据爬取页面
    url(r'^yichuxing_data/$', yichuxing_data, name='yichuxing_data'),  # 宜出行数据爬取
    url(r'^polygon_view/$', polygon_view, name='polygon_view'),  # 矩形范围爬取POI页面
    url(r'^poi_polygon_data/$', poi_polygon_data, name='poi_polygon_data'),  # 矩形范围爬取POI
    url(r'^gridview/$', gridview, name='gridview'),  # 矩形网格生成页面
    url(r'^grid_generate/$', grid_generate, name='grid_generate'),  # 矩形网格生成
    url(r'^boundaryview/$', boundaryview, name='boundaryview'),  # 矩形网格生成页面
    url(r'^boundarydata/$', boundarydata, name='boundarydata'),  # 矩形网格生成
    url(r'^common_file_upload/$', common_file_upload, name='common_file_upload'),  # 文件上传
    url(r'^common_file_download/$', common_file_download, name='common_file_download'),  # 文件下载
    url(r'^common_file_download_coord/$', common_file_download_coord, name='common_file_download_coord'),  # 文件下载
    url(r'^bmappoi/$', bmappoi, name='bmappoi'),  # 百度地图POI数据采集
    url(r'^bmappoidata/$', bmappoidata, name='bmappoidata'),  # 百度地图POI数据采集
    url(r'^common_file_download_yichuxing_chengdu/$', common_file_download_yichuxing_chengdu, name='common_file_download_yichuxing_chengdu'),  # 百度地图POI数据采集



]

izone/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.views.generic import TemplateView

from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import ArticleSitemap, CategorySitemap, TagSitemap
from blog.feeds import AllArticleRssFeed

from rest_framework.routers import DefaultRouter
from api import views as api_views

if settings.API_FLAG:
    router = DefaultRouter()
    router.register(r'users',api_views.UserListSet)
    router.register(r'articles',api_views.ArticleListSet)
    router.register(r'tags',api_views.TagListSet)
    router.register(r'categorys',api_views.CategoryListSet)
    router.register(r'timelines',api_views.TimelineListSet)
    router.register(r'toollinks',api_views.ToolLinkListSet)

# 网站地图
sitemaps = {
    'articles': ArticleSitemap,
    'tags': TagSitemap,
    'categories': CategorySitemap
}

urlpatterns = [
    url(r'^adminx/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),  # allauth
    url(r'^accounts/', include('oauth.urls', namespace='oauth')),  # oauth,只展现一个用户登录界面
    url('', include('blog.urls', namespace='blog')),  # blog
    url(r'^comment/',include('comment.urls',namespace='comment')), # comment
    url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')), # robots
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'), # 网站地图
    url(r'^feed/$', AllArticleRssFeed(), name='rss'),   # rss订阅
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # 加入这个才能显示media文件

if settings.API_FLAG:
    urlpatterns.append(url(r'^api/v1/',include(router.urls,namespace='api')))    # restframework

if settings.TOOL_FLAG:
    urlpatterns.append(url(r'^tool/', include('tool.urls',namespace='tool')))    # tool

apps/tool/models.py
from django.db import models


# Create your models here.

class ToolCategory(models.Model):
    name = models.CharField('网站分类名称', max_length=20)
    order_num = models.IntegerField('序号', default=99, help_text='序号可以用来调整顺序，越小越靠前')

    class Meta:
        verbose_name = '工具分类'
        verbose_name_plural = verbose_name
        ordering = ['order_num', 'id']

    def __str__(self):
        return self.name

class ToolLink(models.Model):
    name = models.CharField('网站名称', max_length=20)
    description = models.CharField('网站描述', max_length=100)
    link = models.URLField('网站链接')
    order_num = models.IntegerField('序号', default=99, help_text='序号可以用来调整顺序，越小越靠前')
    category = models.ForeignKey(ToolCategory, verbose_name='网站分类',blank=True,null=True)

    class Meta:
        verbose_name = '推荐工具'
        verbose_name_plural = verbose_name
        ordering = ['order_num', 'id']

    def __str__(self):
        return self.name

apps/tool/views.py
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.http import JsonResponse
from django.utils.html import mark_safe
from .apis.bd_push import push_urls, get_urls
from .apis.links_test import Check
from .apis.useragent import get_user_agent
from django.http import FileResponse
import re
import markdown

from django.shortcuts import render

import os
import json
import time
import apps.tool.tencendata as tdata
import apps.tool.poi as poi
import apps.tool.poi_polygon as poi_polygon
import apps.tool.heatmap  as heatmap
import apps.tool.coord  as coord
import apps.tool.get_grid as get_grid
from apps.tool.yichuxing import settings, main
from apps.tool.boundary import get_boundary, parse_boundary
from apps.tool.bmappoidata import get_bmap_data
import apps.tool.config as config

FILE_DOWNLOAD_FOLDER = os.getcwd() + os.sep + "apps" + os.sep + "blog" + os.sep + "static" + os.sep + "blog" + os.sep + "commonfile" + os.sep


@require_POST
def common_file_upload(request):
    '''
        公共的文件上传
    '''
    if request.method == "POST":  # 请求方法为POST时，进行处理
        myFile = request.FILES.get("myfile", None)  # 获取上传的文件，如果没有文件，则默认为None
        file_path = os.getcwd() + "/data/upload/" + myFile.name
        if not myFile:
            return JsonResponse(json.loads({"message": "File is None"}))
        destination = open(os.path.join(os.getcwd() + "/data/upload", myFile.name), 'wb+')  # 打开特定的文件进行二进制的写操作
        for chunk in myFile.chunks():  # 分块写入文件
            destination.write(chunk)
        destination.close()
        text = '''{"file_path": "''' + file_path.replace("\\", "\\\\") + '''", "status":"200"}'''
        return JsonResponse(json.loads(text))


def common_file_download(request):
    '''
        公共的文件下载
    '''
    # filename = request.GET['filename']
    filename = " "
    if filename == None or filename == " ":
        filename = 'bmap-poi-boundaey-templete.csv'
    file_full_name = FILE_DOWNLOAD_FOLDER + filename
    print('文件存放地址：', file_full_name)
    file = open(file_full_name, 'rb')
    response = FileResponse(file)
    response['Content-Type'] = 'application/octet-stream'
    response['Content-Disposition'] = 'attachment;filename=' + file_full_name.split(os.sep)[
        len(file_full_name.split(os.sep)) - 1] + ''
    return response


def common_file_download_coord(request):
    '''
        坐标转换模板文件下载
    '''

    filename = " "
    if filename == None or filename == " ":
        filename = 'coord-transform-template.xls'
    file_full_name = FILE_DOWNLOAD_FOLDER + filename
    file = open(file_full_name, 'rb')
    response = FileResponse(file)
    response['Content-Type'] = 'application/octet-stream'
    response['Content-Disposition'] = 'attachment;filename=' + file_full_name.split(os.sep)[
        len(file_full_name.split(os.sep)) - 1] + ''
    return response


def common_file_download_yichuxing_gugong(request):
    '''
        宜出行热力数据模板下载-故宫
    '''

    filename = " "
    if filename == None or filename == " ":
        filename = 'heatdata--gugong-2019-11-29-10-13-36.csv'
    file_full_name = FILE_DOWNLOAD_FOLDER + filename
    file = open(file_full_name, 'rb')
    response = FileResponse(file)
    response['Content-Type'] = 'application/octet-stream'
    response['Content-Disposition'] = 'attachment;filename=' + file_full_name.split(os.sep)[
        len(file_full_name.split(os.sep)) - 1] + ''
    return response



def common_file_download_yichuxing_chengdu(request):
    '''
        宜出行热力数据模板下载-成都
    '''

    filename = " "
    if filename == None or filename == " ":
        filename = 'heatdata--gugong-2019-11-29-10-13-36.csv'
    file_full_name = FILE_DOWNLOAD_FOLDER + filename
    file = open(file_full_name, 'rb')
    response = FileResponse(file)
    response['Content-Type'] = 'application/octet-stream'
    response['Content-Disposition'] = 'attachment;filename=' + file_full_name.split(os.sep)[
        len(file_full_name.split(os.sep)) - 1] + ''
    return response



# Create your views here.

def Toolview(request):
    return render(request, 'tool/tool.html')


# 百度主动推送
def BD_pushview(request):
    return render(request, 'tool/bd_push.html')


@require_POST
def bd_api_view(request):
    if request.is_ajax():
        data = request.POST
        url = data.get('url')
        urls = data.get('url_list')
        info = push_urls(url, urls)
        return JsonResponse({'msg': info})
    return JsonResponse({'msg': 'miss'})


# 百度主动推送升级版，提取sitemap链接推送
def BD_pushview_site(request):
    return render(request, 'tool/bd_push_site.html')


@require_POST
def bd_api_site(request):
    if request.is_ajax():
        data = request.POST
        url = data.get('url')
        map_url = data.get('map_url')
        urls = get_urls(map_url)
        if urls == 'miss':
            info = "{'error':404,'message':'sitemap地址请求超时，请检查链接地址！'}"
        elif urls == '':
            info = "{'error':400,'message':'sitemap页面没有提取到有效链接，sitemap格式不规范。'}"
        else:
            info = push_urls(url, urls)
        return JsonResponse({'msg': info})
    return JsonResponse({'msg': 'miss'})


# 友链检测
def Link_testview(request):
    return render(request, 'tool/link_test.html')


@require_POST
def Link_test_api(request):
    if request.is_ajax():
        data = request.POST
        p = data.get('p')
        urls = data.get('urls')
        c = Check(urls, p)
        info = c.run()
        return JsonResponse(info)
    return JsonResponse({'msg': 'miss'})


# 在线正则表达式
def regexview(request):
    return render(request, 'tool/regex.html')


@require_POST
def regex_api(request):
    if request.is_ajax():
        data = request.POST
        texts = data.get('texts')
        regex = data.get('r')
        try:
            lis = re.findall(r'{}'.format(regex), texts)
        except:
            lis = []
        num = len(lis)
        info = '\n'.join(lis)
        result = "匹配到&nbsp;{}&nbsp;个结果：\n".format(num) + "```\n" + info + "\n```"
        result = markdown.markdown(result, extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
        ])
        return JsonResponse({'result': mark_safe(result), 'num': num})
    return JsonResponse({'msg': 'miss'})


# 生成请求头
def useragent_view(request):
    return render(request, 'tool/useragent.html')


@require_POST
def useragent_api(request):
    if request.is_ajax():
        data = request.POST
        d_lis = data.get('d_lis')
        os_lis = data.get('os_lis')
        n_lis = data.get('n_lis')
        d = d_lis.split(',') if len(d_lis) > 0 else None
        os = os_lis.split(',') if len(os_lis) > 0 else None
        n = n_lis.split(',') if len(n_lis) > 0 else None
        result = get_user_agent(os=os, navigator=n, device_type=d)
        return JsonResponse({'result': result})
    return JsonResponse({'msg': 'miss'})


# HTML特殊字符对照表
def html_characters(request):
    return render(request, 'tool/characters.html')


# 腾讯位置大数据爬取-页面
def tencentview(request):
    return render(request, 'tool/tencent.html')


# 腾讯位置大数据爬取
def tencent_data(request):
    max_lon = request.GET['max_lon']
    min_lon = request.GET['min_lon']
    max_lat = request.GET['max_lat']
    min_lat = request.GET['min_lat']

    if len(max_lon) > 5:
        max_lon = max_lon[0:5]
    if len(min_lon) > 5:
        min_lon = min_lon[0:5]

    if len(max_lat) > 4:
        max_lat = max_lat[0:4]
    if len(min_lat) > 4:
        min_lat = min_lat[0:4]

    if (max_lon is None or max_lon is ''):
        return render(request, 'tool/tencent.html', {'message': '请输入完整的范围经纬度!'})
    if (min_lon is None or max_lon is ''):
        return render(request, 'tool/tencent.html', {'message': '请输入完整的范围经纬度!'})
    if (max_lat is None or max_lon is ''):
        return render(request, 'tool/tencent.html', {'message': '请输入完整的范围经纬度!'})
    if (min_lat is None or max_lon is ''):
        return render(request, 'tool/tencent.html', {'message': '请输入完整的范围经纬度!'})

    try:
        max_lon = int(max_lon)
        min_lon = int(min_lon)
        max_lat = int(max_lat)
        min_lat = int(min_lat)
    except Exception as e:
        return render(request, 'tool/tencent.html', {'message': '请输入整数类型的经纬度'})

    tdata.max_lon_default = max_lon
    tdata.min_lon_default = min_lon
    tdata.max_lat_default = max_lat
    tdata.min_lat_default = min_lat

    flag = True
    now_time_str = str(time.strftime('%Y-%m-%d-%H-%M-%S', time.localtime(time.time())))
    file_name = "TecentData-" + now_time_str + ".csv"
    while (flag):
        for i in range(4):
            try:
                tdata.get_TecentData(4, i, file_name)  # 主要是循环count，来获取四个链接里的数据
            except Exception as e:
                return render(request, 'tencent.html', {'message': '爬取失败，请联系管理员'})
        flag = False

        file_path = os.getcwd() + "/" + file_name

        file = open(file_path, 'rb')
        response = FileResponse(file)
        response['Content-Type'] = 'application/octet-stream'
        response['Content-Disposition'] = 'attachment;filename=' + file_name + ''
        return response


def poi_view(request):
    return render(request, 'tool/poi.html')


@require_POST
def poi_data(request):
    '''
    根据关键字爬取POI数据
    :param request:
    :return:
    '''

    data = request.POST
    city = data.get('city')
    province = data.get('province')
    keyword = data.get('keyword')
    key = data.get('key')  # "4188efb67360681f89110ccdb11e563b"
    coord = data.get('coord')

    # TODO:
    # province = "500000"
    # keyword = "大学"
    # key = "9f27cbb8d65567505df8cae9dac49aa3"

    if (province == None or province == ""):
        return render(request, 'tool/poi.html', {'message': "城市或直辖市不能为空"})
    if (keyword == None or keyword == ""):
        return render(request, 'tool/poi.html', {'message': "POI关键字不能为空"})
    #    if (key == None or key == ""):
    # return render(request, 'tool/poi.html',  {'message':"密钥不能为空，如有需要请自行申请或者联系917961898获取"})

apps/tool/templates/tool/bmappoi.html
{% extends "tool/base_tool.html" %} {% load static %}

{% block head_title %}百度POI数据采集{% endblock %} {% block metas %}
<meta name="description" content="基于百度地图开放平台API接口实现的POI数据在线采集工具">
<meta name="keywords" content="百度POI,百度POI采集,百度地图POI,POI采集,POI采集工具"> {% endblock %} {% block tool_name %}百度POI数据采集{% endblock %} {% block left_content %}
<div class="card-body p-0">
	<h3 class="card-title pl-2 title-info">工具说明：</h3>
	<ul>
		<li>基于百度地图实现的POI数据采集工具,可以采集指定经纬度范围内的POI</li>
		<li>首先需要确定爬取 的范围，使用<a target="_blank" style="margin-top:30px;color:#33ABA0" href="{% url 'tool:coordpick' %}">坐标拾取系统</a>采集经纬度范围，将最大、最小的经纬度填入下面的表格中。</li>
		<li>其次，需要在百度地图API开放平台申请百度密钥。</li>
		<li>数据可视化：<a target="_blank" style="margin-top:30px;color:#33ABA0" href="{% url 'tool:poi_visual' %}">点击这里</a></li>
		<li>坐标转换：<a style="margin-top:30px;color:#33ABA0" href="{% url 'tool:coord_view' %}">点击这里</a></li>
	</ul>
</div>
<form method="post" action="{% url 'tool:bmappoidata' %}">
	{% if message %}
	<div class="alert alert-danger" role="alert">{{ message }}</div>
	{% endif %}
	
	<div class="mb-3">
		<div class="form-group">
	        <label>最大经度：</label>
	        <input type="text" class="form-control " value="114.00650422835264" name="max_lon"
	               placeholder="例如：115.34343"
	               required>
	        <small class="form-text text-muted">注：</small>
	    </div>
	    <div class="form-group">
	        <label>最小经度：</label>
	        <input type="text" class="form-control" value="113.80650422835264" name="min_lon"
	               placeholder="例如：115.1234"
	               required>
	        <small class="form-text text-muted">注：</small>
	    </div>
	    <div class="form-group">
	        <label>最大纬度：</label>
	        <input type="text" class="form-control" value="22.803672722381442" name="max_lat"
	               placeholder="例如：32.703455"
	               required>
	        <small class="form-text text-muted">注：</small>
	    </div>
	    <div class="form-group">
	        <label>最小纬度：</label>
	        <input type="text" class="form-control" value="22.603672722381442" name="min_lat"
	               placeholder="例如：31.153543"
	               required>
	        <small class="form-text text-muted">注：</small>
	    </div>
		<div class="form-group">
			<label>分类关键字：</label>
			<input type="text" class="form-control" name="keyword" placeholder="例如：住宅区" required>
			<small class="form-text text-muted">注：</small>
		</div>
		<div class="form-group">
			<label>百度密钥：</label>
			<input type="text" class="form-control" name="key" placeholder="" required>
			<small class="form-text text-muted">注：自己去百度开放平台申请，类型记得是web服务，而不是web端等其他</small>
		</div>
		<div class="form-group">
			<label>坐标系：</label>
			<select id="coord" class="form-control" style="width: :100px;" name="coord">
				<option value="">直接选择或搜索选择</option>
				<option value="1">高德坐标系</option>
				<option value="2">WGS84坐标系</option>
				<option value="3">百度坐标系</option>
			</select>
			<small class="form-text text-muted">注：</small>
		</div>
		<button type="submit" class="btn btn-info btn-sm rounded-0">确定</button>

	</div>

	{% csrf_token %}
</form>

<div style="height:100px;margin-left:100px">
	<a style="margin-top:30px;color:#33ABA0" href="{% url 'tool:poi_visual' %}">你可能还需POI数据可视化工具？点击这里快速实现可视化</a>
</div>

{% endblock %} {% block end_f %} {% endblock %}

apps/tool/templates/tool/polygon.html
{% extends "tool/base_tool.html" %} {% load static %}

<link href="{% static 'tool/css/layui.css' %}?v=20180107.08" rel="stylesheet"> {% block head_title %}POI矩形网格爬取{% endblock %} {% block metas %}
<meta name="description" content="采用划分矩形网格的方式来采集大范围内的高德POI数据，可以成功避开接口只返回900条数据的限制">
<meta name="keywords" content="高德POI矩形网格爬取,网格爬取,POI网格爬取,POI网格划分,POI矩形"> {% endblock %} {% block tool_name %}POI数据爬取{% endblock %} {% block left_content %}
<div class="card-body p-0">
	<h3 class="card-title pl-2 title-info">工具说明：</h3>
	<ul>
		<li>根据指定的城市划分为N多个矩形分别爬取高德POI数据，相比根据关键字爬取，数据量更为完整</li>
		<li>由于服务器性能问题，最好下载代码在本地运行：地址：https://github.com/liujiao111/poi, 里面的poi-pology文件夹</li>
		<li>城市：确定需要爬取的城市名，目前不支持多城市爬取，一次只能爬取一个城市的数据</li>
		<li>数据可视化：<a style="margin-top:30px;color:#33ABA0" href="{% url 'tool:poi_visual' %}">点击这里</a></li>
		<li>坐标转换：<a style="margin-top:30px;color:#33ABA0" href="{% url 'tool:coord_view' %}">点击这里</a></li>
	</ul>
</div>
<form method="post" action="{% url 'tool:poi_polygon_data' %}">
	{% if message %}
	<p style="color:red;margin-left:150px;;height:30px;margin-bottom:20px">{{ message }}</p>
	{% endif %}
	<div class="mb-3">
		<div class="form-group">
			<label>城市：</label>
			<div class="row" style="margin-left: 10px;">
				<div class="col-xs-3">
					<select id="province" onchange="selectProvince()" class="form-control" name="province" style="width: :100px;">
						<option value="">请选择省或者直辖市</option>
						<option value="410000">河南省</option>
						<option value="440000">广东省</option>
						<option value="150000">内蒙古自治区</option>
						<option value="230000">黑龙江省</option>
						<option value="650000">新疆维吾尔自治区</option>
						<option value="420000">湖北省</option>
						<option value="210000">辽宁省</option>
						<option value="370000">山东省</option>
						<option value="320000">江苏省</option>
						<option value="610000">陕西省</option>
						<option value="310000">上海市</option>
						<option value="520000">贵州省</option>
						<option value="500000">重庆市</option>
						<option value="540000">西藏自治区</option>
						<option value="340000">安徽省</option>
						<option value="350000">福建省</option>
						<option value="430000">湖南省</option>
						<option value="460000">海南省</option>
						<option value="630000">青海省</option>
						<option value="450000">广西壮族自治区</option>
						<option value="640000">宁夏回族自治区</option>
						<option value="360000">江西省</option>
						<option value="330000">浙江省</option>
						<option value="130000">河北省</option>
						<option value="810000">香港特别行政区</option>
						<option value="710000">台湾省</option>
						<option value="820000">澳门特别行政区</option>
						<option value="620000">甘肃省</option>
						<option value="510000">四川省</option>
						<option value="220000">吉林省</option>
						<option value="120000">天津市</option>
						<option value="530000">云南省</option>
						<option value="110000">北京市</option>
						<option value="140000">山西省</option>

					</select>
				</div>
				<div class="col-xs-3" style="margin-left: 20px;">
					<select id="city" class="form-control" style="width: :100px;" name="city">
						<option value="">请选择市</option>
					</select>
				</div>

			</div>
		</div>
		<div class="form-group">
			<label>分类关键字：</label>
			<input type="text" class="form-control" name="keyword" placeholder="例如：酒店" required>
			<small class="form-text text-muted">注：</small>
		</div>
		<div class="form-group">
			<label>高德密钥：</label>
			<input type="text" class="form-control" name="key" placeholder="" required>
			<small class="form-text text-muted">注：自己去高德开放平台申请，类型记得是web服务，而不是web端等其他</small>
		</div>
		<div class="form-group">
			<label>坐标系：</label>
			<select id="coord" class="form-control" style="width: :100px;" name="coord">
				<option value="">直接选择或搜索选择</option>
				<option value="1">高德坐标系</option>
				<option value="2">WGS84坐标系</option>
				<option value="3">百度坐标系</option>

			</select>
			<small class="form-text text-muted">注：</small>
		</div>
		<button type="submit" class="btn btn-info btn-sm rounded-0">确定</button>

	</div>

	{% csrf_token %}
</form>

<div style="height:100px;margin-left:100px">
	<a style="margin-top:30px;color:#33ABA0" href="{% url 'tool:poi_visual' %}">你可能还需POI数据可视化工具？点击这里快速实现可视化</a>
</div>

<script type="text/javascript" src="../../static/tool/js/distrinct.js"></script>
<script type="text/javascript">
	function selectProvince(e) {
		var provinceCode = $("#province").val();
		if(provinceCode == null || provinceCode == "") {
			return;
		}

		$("#city").empty();
		$("#city").append("<option value=''>请选择城市</option>")

		$.ajax({
			type: "get",
			url: "{% url 'tool:subdistrict_data' %}",
			data: {
				code: provinceCode
			},
			async: true,
			success: function(data) {

				craeteOptions(data);

			}
		});
	}

	function craeteOptions(data) {
		//data = $.parseJSON(data);
		console.log(data.districts[0].districts.length);

		var districts = data.districts[0].districts;

		for(var i = 0; i < districts.length; i++) {
			$("#city").append("<option value=" + districts[i].adcode + ">" + districts[i].name + "</option>")
		}
	}
</script>

{% endblock %} {% block end_f %} {% endblock %}